MoneyTransfer/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MoneyTransfer.Models;
using MoneyTransfer.ViewModels;

namespace MoneyTransfer.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly UserManager<User> _userManager;
        public ApplicationContext context;

        public TransactionsController(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult CreateTransaction()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTransaction(TransactionsViewModel model)
        {
            if (ModelState.IsValid)
            {
                User userOut = await _userManager.FindByNameAsync(model.PersonalAccountOut.ToString());
                User userIn = await _userManager.FindByNameAsync(model.PersonalAccountIn.ToString());

                if (userOut.Balance >= model.Summa)
                {
                    userOut.Balance = userOut.Balance - model.Summa;
                    userIn.Balance = userIn.Balance + model.Summa;
                    Transactions transactions = new Transactions()
                    {
                        PersonalAccountOut = userOut.Id,
                        PersonalAccountIn = userIn.Id,
                        Summa = model.Summa,
                        DateTime = DateTime.Now.ToString("MM/dd/yyyy")
                    };

                    _userManager.UpdateAsync(userIn);
                    _userManager.UpdateAsync(userOut);
                    context.Transactionses.Update(transactions);
                    await context.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult ReplenishmentOfFunds()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ReplenishmentOfFunds(TransactionsViewModel model)
        {
            User userIn = await _userManager.FindByNameAsync(model.PersonalAccountIn.ToString());
            userIn.Balance = userIn.Balance + model.Summa;
            await _userManager.UpdateAsync(userIn);
            Transactions transactions = new Transactions()
            {
                PersonalAccountIn = userIn.UserName,
                Summa = model.Summa,
                DateTime = DateTime.Now.ToString("MM/dd/yyyy")
            };
            context.Update(transactions);
            await context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> MyTranzaction()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            IQueryable<Transactions> transactions = context.Transactionses.Where(t => t.PersonalAccountIn == user.UserName.ToString() || t.PersonalAccountOut == user.UserName.ToString());
            return View(transactions);
        }
    }
}

MoneyTransfer/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["MoneyTransfer"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MoneyTransfer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="HomeUserPage">@User.Identity.Name</a></li>
                        <li>
                            <a>
                                <form method="post" asp-controller="Account" asp-action="LogOff">
                                    <input type="submit" value="@Localizer["Out"]" />
                                </form>
                            </a>
                        </li>

                    }
                    else
                    {
                        <li>
                            <a asp-controller="Account" asp-action="Login">@Localizer["Login"]</a>
                        </li>
                        <li>
                            <a asp-controller="Account" asp-action="Register">@Localizer["Register"]</a>
                        </li>
                    }
                    <li><a asp-controller="Transactions" asp-action="Index">@Localizer["Tranzaction"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">@Localizer["About"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">@Localizer["Contact"]</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MoneyTransfer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>